services:
  - type: web
    name: express-app
    plan: free  # or starter/standard based on your plan
    branch: main
    runtime: node  # Specify Node.js runtime
    buildCommand: 'npm install && npm run build && npm test'  # Install, build, and run tests
    startCommand: 'npm run start'
    autoDeploy: false  # Disable automatic deploy to handle it via GitHub Actions
